# Generated by Django 4.2 on 2024-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Начальник'), ('assistant', 'Помощник')], default='employee', max_length=10),
        ),
    ]
