# Generated by Django 4.2 on 2024-12-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'assigned_to'], name='documents_d_status_60715b_idx'),
        ),
    ]
